name:                dailyReps
version:             0.1.0.0
github:              "githubuser/dailyReps"
license:             BSD3
author:              "Sebastian Enguidanos"
maintainer:          "senguidanos@gmail.com"
copyright:           "2020 Sebastian Enguidanos"

extra-source-files:
- README.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/githubuser/dailyReps#readme>

dependencies:
- base >= 4.7 && < 5

library:
  source-dirs: haskell

ghc-options:
  - -Wall
  - -Werror
